version: '3'

services:

  pnj-rmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - "default"

  pnj-db:
    image: "mariadb"
    container_name: "pnj-db"
    hostname: "pnj-db"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - "3306:3306"
    networks:
      - "default"
    volumes:
      - "./var/mysql:/var/lib/mysql"

  pnj-adminer:
    image: "adminer"
    container_name: "pnj-adminer"
    hostname: "pnj-adminer"
    ports:
      - "8080:8080"
    networks:
      - "default"

networks:
  default:
    driver: "bridge"
